### ISSUE TITLE
Issue installing on systems with lower resource levels

### ISSUE THREAD

**Issue by eklein** [chef/dep-selector-libgecode#18]
In attempting to bundle install on a system with only 2 processors and 2G RAM, we ran out of memory repeatedly.  I believe that this can be directly attributed to the `make -j 5` found in `ext/libgecode3/extconf.rb`.

Here's an example of the error:

```
{standard input}: Assembler messages:
{standard input}:420981: Warning: end of file not at end of a line; newline inserted
{standard input}:421008: Error: suffix or operands invalid for `sal'
{standard input}:421008: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: Internal error: Killed (program cc1plus)
Please submit a full bug report.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[1]: *** [gecode/int/branch/post-view-int.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/buildslave-03/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/dep-selector-libgecode-1.0.0/ext/libgecode3/vendor/gecode-3.7.3'
make: *** [compilelib] Error 2
extconf.rb:89:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
	from extconf.rb:88:in `chdir'
	from extconf.rb:88:in `run'
	from extconf.rb:95:in `<main>'
```

Watching the memory in another window shows us exhaust physical memory quickly and dip into swap almost immediately.  Just before the above error, the system runs out of memory.

Running this by hand using `make` or `make -j 2` makes it work just fine.  As another datapoint, running this on a beefier machine (my macbook pro w/ 16GB), it still took ages to build, but it worked.

I will submit a PR to change that from `make -j 5` to `make` if that's reasonable.  This will cause it to take more time in building, but will allow to build properly on systems with fewer processors and less RAM.

**Comment by lamont-granquist** [comment]
1.  chef-dk
2.  GECODE_MAKE_CONCURRENCY_LEVEL=1
3.  #52 / #53 and use a virt with 1 vCPU
