### ISSUE TITLE
Build fails on Windows 8.1 with cygwin (tar)

### ISSUE THREAD

**Issue by phromo** [chef/dep-selector-libgecode#27]
Problem
=======
If building on windows with cygwin tar in path
Then a hpp file is generated in a way that requires administrative access
and the build fails:

auto-link.hpp: Permission denied
Compilation terminated

Workaround:
----------------
* elevate command prompt prior to install
or
* manually modify permissions of file giving CreaterOwner full access:

takeown /F "c:\ruby200" /R
icacls "c:\ruby200" /grant "creator owner":(OI)(CI)F

Background:
---------------
> which tar
/usr/bin/tar

> ruby -version
2.0.0p195 (2013-05-14) [i386-mingw32]

**Comment by neillturner** [comment]
I hate to say it but this code is horribly broken if it relies on a tar executable to be available. This absolutely doesn't work on windows. All the gems like berkshelf that rely on his gem are horribly broken on windows as well i'm afraid.

**Comment by phromo** [comment]
I've worked around these issues by using the chef development kit (chef dk) that comes with everything prebuilt

**Comment by lamont-granquist** [comment]
we don't support cygwin.  using chef-dk will get you an msys environment which will be less painful.
