### ISSUE TITLE
Error installing dep-selector-libgecode: Failed to build gem native extension.(Windows, ruby 2.0.0p481)

### ISSUE THREAD

**Issue by kalfaro** [chef/dep-selector-libgecode#28]
C:\windows\system32>gem install dep-selector-libgecode -v '1.0.2'
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing dep-selector-libgecode:
        ERROR: Failed to build gem native extension.

    C:/Ruby200/bin/ruby.exe extconf.rb
checking for the host operating system... Windows
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for diff... ok
checking for tar... no
configure: error: In order to compile Gecode, you need the tar tool.
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::B
uildError)
        from extconf.rb:97:in `chdir'
        from extconf.rb:97:in `run'
        from extconf.rb:104:in `<main>'
-> sh C:/Ruby200/lib/ruby/gems/2.0.0/gems/dep-selector-libgecode-1.0.2/ext/libge
code3/vendor/gecode-3.7.3/configure --prefix=C:/Ruby200/lib/ruby/gems/2.0.0/gems
/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode --disab
le-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disabl
e-doc-docset --disable-qt --disable-examples --disable-flatzinc --with-host-os=w
indows

Gem files will remain installed in C:/Ruby200/lib/ruby/gems/2.0.0/gems/dep-selec
tor-libgecode-1.0.2 for inspection.
Results logged to C:/Ruby200/lib/ruby/gems/2.0.0/gems/dep-selector-libgecode-1.0
.2/ext/libgecode3/gem_make.out

**Comment by mattwcole** [comment]
In my case this turned out to be an issue with the version of tar.exe that comes with git for windows (1.9.5-preview). I changed this for the version that comes with the ChefDK and it built without error.

**Comment by lamont-granquist** [comment]
the solution here is going to be to point you to chef-dk on windows.   hand building this gem on windows is going to be difficult, which is why we have chef-dk.
