### ISSUE TITLE
Cygwin "C++ compiler cannot create executables"

### ISSUE THREAD

**Issue by electrawn** [chef/dep-selector-libgecode#36]
/usr/bin/ruby.exe -r ./siteconf20141014-6460-phqvtx.rb extconf.rb
-> sh /home/build/.gem/ruby/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3/configure --prefix=/home/build/.gem/ruby/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode --disable-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disable-doc-docset --disable-qt --disable-examples --disable-flatzinc

checking for the host operating system... Windows
checking whether the C++ compiler works... no
configure: error: in `/home/build/.gem/ruby/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
        from extconf.rb:97:in `chdir'
        from extconf.rb:97:in `run'
        from extconf.rb:104:in `<main>'

extconf failed, exit code 1

Patch fix is: https://github.com/opscode/dep-selector-libgecode/pull/23

Workaround:
CC=g++ gem install dep-selector-libgecode

**Comment by troyready** [comment]
I've been looking into this a bit too, and it seems that when compiling the gem on windows a better distinction should be drawn between:

1) operating solely in cygwin
or
2) compiling for use in native windows

I think this mainly affects modifying ext/libgecode3/extconf.rb (which I think could eliminate the need for patch #23). Would it make sense to add another environment variable to configure these options (like omitting the mingw pthread gsub)?

Alternatively, if this broadens the support scope too much for the gem, perhaps the documentation could be updated to recommend using USE_SYSTEM_GECODE when in cygwin?

**Comment by troyready** [comment]
Disregard my last comment above -- the embedded build is working properly for me out of the box with just `export CC=gcc`, `export CXX=g++`, and ensuring bsdtar is installed (may be unnecessary, but seems to be sought by the config file).

**Comment by lamont-granquist** [comment]
we don't and never have supported cygwin.
