### ISSUE TITLE
./configure fails because of bashisms

### ISSUE THREAD

**Issue by bougyman** [chef/dep-selector-libgecode#46]
The shebang in the ./configure script is #!/bin/sh, however there are many bashisms used in it. This causes a syntax error on line 11561 with dash, ash, and other minimal sh providers, and the script cannot proceed, building stops. This shebang should be #!/bin/bash, at which point everything works well.

**Comment by coderanger** [comment]
Hmm, not sure we want to fix bugs in actual gecode. The point is to vendor it as is to make it easier to install, not to take over management of gecode as a library.

**Comment by bougyman** [comment]
Ah, then this issue is on the wrong project. Will add it to upstream gecode. Thanks.
